# Generated by Django 4.0.4 on 2022-05-13 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('idalmacen', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nmbalmacen', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'almacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('idbodega', models.BigIntegerField(primary_key=True, serialize=False)),
                ('capacidadmaxima', models.BigIntegerField()),
            ],
            options={
                'db_table': 'bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idcomuna', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nmbcomuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaUsuario',
            fields=[
                ('idcuentausuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nmbusuario', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cuenta_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nmbpais', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechapedido', models.DateField()),
                ('pedidoanulado', models.CharField(max_length=1)),
                ('pedidorecibido', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('stockminimo', models.BigIntegerField()),
                ('stockmaximo', models.BigIntegerField()),
                ('preciocompra', models.BigIntegerField()),
                ('precioventa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrolote', models.BigIntegerField()),
                ('fechavenc', models.DateField()),
                ('cantidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'producto_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nmbproveedor', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=320)),
                ('fono', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idregion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nmbregion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idtipoproducto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nmbtipoproducto', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idtipousuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nmbtipousuario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoLine',
            fields=[
                ('idpedido', models.OneToOneField(db_column='idpedido', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.pedido')),
                ('cantidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pedido_line',
                'managed': False,
            },
        ),
    ]
