# Generated by Django 4.0.4 on 2022-06-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idprovincia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
